### ISSUE TITLE
A06 image needs to be updated - BADLY- for better out-of-box updating (cert out of date from the get-go)

### ISSUE THREAD

**Issue by Waethorn** [clockworkpi/uConsole#15]
Dunno about the other images, but this one has an out-of-date certificate that prevents software updates.  Getting it to work requires a lot of work that regular users would find extremely daunting (very little guidance or information online about this - I had trouble finding it), leaving them horrible out-of-date with security updates.  Will update with more information after more testing.

**Comment by Paru-paru** [comment]
I get this when I download the A06 image.
![Screenshot from 2024-01-27 18-02-51](https://github.com/clockworkpi/uConsole/assets/120796221/79246da5-8e01-42b7-b890-43eb79ed7a55)
Not sure if its just out of date but its not the same numbers thats on the wiki

**Comment by Waethorn** [comment]
Try updating it and see if you get errors.
